export const locations = [
  // Unidades Tradicionais
  {
    id: "cachoeirinha",
    name: "Cachoeirinha",
    address: "Av. Ajuricaba, 660, Cachoeirinha",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/1-300x228.png",
    hotsite: "https://cachoeirinha.hotsite.in",
    mapLink: "https://maps.app.goo.gl/CJSbpBvduqqwtUqv9",
    viewLink: "https://www.liveacademia.com.br/unidades/cachoeirinha/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/CJSbpBvduqqwtUqv9",
  },
  {
    id: "camapua", 
    name: "Camapuã",
    address: "Av. Camapuã, 53, Cidade de Deus",
    hours: "Seg-Sex: 5h30-22h | Sáb: 8h-17h | Dom: 8h-14h | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "Atendimento domingos", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/6-300x228.png",
    hotsite: "https://livemcamapua.hotsite.in",
    mapLink: "https://maps.app.goo.gl/fZ9sGn8n2HoHsTSM7",
    viewLink: "https://www.liveacademia.com.br/unidades/camapua/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/fZ9sGn8n2HoHsTSM7",
  },
  {
    id: "centro",
    name: "Centro",
    address: "Av. Getúlio Vargas, 773, Centro",
    hours: "Seg-Sex: 5h-22h | Sáb: 8h-17h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/CENTRO-300x228.png",
    hotsite: "https://centro.hotsite.in",
    mapLink: "https://maps.app.goo.gl/Vms8fJVQFbn2XNtx9",
    viewLink: "https://www.liveacademia.com.br/unidades/centro/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/Vms8fJVQFbn2XNtx9",
  },
  {
    id: "chapeu-goiano",
    name: "Chapéu Goiano",
    address: "Rua Lirio do Mar, 15, Cidade Nova",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/37-300x228.png",
    hotsite: "https://livechapeugoiano.hotsite.in",
    mapLink: "https://maps.app.goo.gl/JZ7y9arDVtebH9EX7",
    viewLink: "https://www.liveacademia.com.br/unidades/chapeu-goiano/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/JZ7y9arDVtebH9EX7",
  },
  {
    id: "cidade-de-deus",
    name: "Cidade de Deus", 
    address: "Av. Nossa Sra. da Conceição, 830, Cidade de Deus",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/13-300x228.png",
    hotsite: "https://livecidadededeus.hotsite.in",
    mapLink: "https://maps.app.goo.gl/DLf1asqUsmJRQMSz5",
    viewLink: "https://www.liveacademia.com.br/unidades/cidade-de-deus/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/DLf1asqUsmJRQMSz5",
  },
  {
    id: "compensa",
    name: "Compensa",
    address: "Av. Padre Agostinho Caballero Martin, 115, Compensa", 
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/8-300x228.png",
    hotsite: "https://compensa.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/ab23foNLjQYrZLXQ6",
    viewLink: "https://www.liveacademia.com.br/unidades/compensa/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/ab23foNLjQYrZLXQ6",
  },
  {
    id: "dom-pedro",
    name: "Dom Pedro",
    address: "Av. Dom Pedro I, 27, Dom Pedro",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/14-300x228.png",
    hotsite: "https://livedompedro.hotsite.in/",
    mapLink: "https://maps.app.goo.gl/21EYnddqV8PWYq3v7",
    viewLink: "https://www.liveacademia.com.br/unidades/dom-pedro/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/21EYnddqV8PWYq3v7",
  },
  {
    id: "japiim",
    name: "Japiim",
    address: "Rua Fernando de Cordoba, 597, Japiim",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/9-300x228.png",
    hotsite: "https://livejapiim.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/SeTgq9Lr5fmPuXk16",
    viewLink: "https://www.liveacademia.com.br/unidades/japiim/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/SeTgq9Lr5fmPuXk16",
  },
  {
    id: "silves",
    name: "Silves",
    address: "Av. Silves, 187, Raiz",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/09/15-300x228.png",
    hotsite: "https://silves.hotsite.in",
    mapLink: "https://maps.app.goo.gl/yPkLiUN7SgcGBAM4A",
    viewLink: "https://www.liveacademia.com.br/unidades/silves/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/yPkLiUN7SgcGBAM4A",
  },
  {
    id: "sumauma",
    name: "Sumaúma",
    address: "Av. Bispo Pedro Massa, 306",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/10-300x228.png",
    hotsite: "https://livesumauma.hotsite.in",
    mapLink: "https://maps.app.goo.gl/fPr7KRcjLwmt6Juy7",
    viewLink: "https://www.liveacademia.com.br/unidades/samauma/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/fPr7KRcjLwmt6Juy7",
  },
  {
    id: "tiradentes",
    name: "Tiradentes Climatizada",
    address: "Rua das Rosas, 107, Aleixo",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "Climatização", "App acesso"],
    type: "premium",
    status: "open", 
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/11-300x228.png",
    hotsite: "https://livetiradentes.hotsite.in",
    mapLink: "https://maps.app.goo.gl/5rengWk3dygYPW7R7",
    viewLink: "https://www.liveacademia.com.br/unidades/tiradentes/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/5rengWk3dygYPW7R7",
  },
  {
    id: "torquato-allegro",
    name: "Torquato Allegro",
    address: "Av. Torquato Tapajós, 6950, Tarumã",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/16-300x228.png",
    hotsite: "https://allegro.hotsite.in",
    mapLink: "https://maps.app.goo.gl/dKNMMUbU2Ttrm6xY6",
    viewLink: "https://www.liveacademia.com.br/unidades/torquato-allegro/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/dKNMMUbU2Ttrm6xY6",
  },
  {
    id: "torquato-bemol",
    name: "Torquato Bemol Climatizada",
    address: "Av. Torquato Tapajós, 8160, Colônia Terra Nova",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "Climatização", "App acesso"],
    type: "premium",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/2-300x228.png",
    hotsite: "https://evo-totem.w12app.com.br/liveacademia/12/site/KKpgxGRZNJI%5BPLUS%5D%5BBAR%5DXC4KLnl5Q%5BEQUAL%5D%5BEQUAL%5D",
    mapLink: "https://maps.app.goo.gl/WUHoxxiqmJwwGN2c9",
    viewLink: "https://www.liveacademia.com.br/unidades/torquato-bemol/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/WUHoxxiqmJwwGN2c9",
  },
  {
    id: "torquato-santos-dumont",
    name: "Torquato Santos Dumont",
    address: "Av. Torquato Tapajós, 5555, Da Paz",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/7-300x228.png",
    hotsite: "https://livetorquato1.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/fr4yv2Cz6enftDc99",
    viewLink: "https://www.liveacademia.com.br/unidades/torquato-santos-dumont/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/fr4yv2Cz6enftDc99",
  },
  {
    id: "torres", 
    name: "Torres",
    address: "Rua Mitiko, 397, Parque Dez de Novembro",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Aulas coletivas", "App acesso"],
    type: "tradicional",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/12-300x228.png",
    hotsite: "https://liveacademiastorres.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/V8a9D7bnWy6WHFgAA",
    viewLink: "https://www.liveacademia.com.br/unidades/torres/",
    planos: [
      { name: "Assinatura Basic s/Fidelidade", price: "119,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/V8a9D7bnWy6WHFgAA",
  },
  
  // Unidades Diamante/Premium
  {
    id: "bom-prato-diamante",
    name: "Bom Prato Diamante",
    address: "R. Santa Cecília, 165 - Col. Santo Antônio (Bom Prato)",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/10/CIDADE-NOVA-DIAMANTE-1-300x300.jpg",
    hotsite: "https://bomprato.hotsite.in",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/cidade-nova-diamante/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "",
  },
  {
    id: "ct-cidade-nova",
    name: "CT Cidade Nova",
    address: "Av. Max Teixeira, Nº 4066 - Cidade Nova",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open", 
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/10/CT-300x228.png",
    hotsite: "https://liveacademiacidadenova.hotsite.in/home",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/cidade-nova-premium/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "",
  },
  {
    id: "flores-diamante",
    name: "Flores Diamante",
    address: "R. Visc. de Sepetiba, 220 - Flores",
    hours: "Seg-Sex: 5h-24h | Sáb: 8h-17h | Dom: 8h-14h | Feriado: 7h-17h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Espaço Pose", "Studio de Bike", "Aulas coletivas", "Climatização", "Atendimento domingos", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/06/27-300x228.png",
    hotsite: "https://liveacademiaflores.hotsite.in",
    mapLink: "https://g.co/kgs/QbPquLE",
    viewLink: "https://www.liveacademia.com.br/unidades/flores-diamante/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://g.co/kgs/QbPquLE",
  },
  {
    id: "margarita-diamante",
    name: "Margarita Diamante", 
    address: "Av. Margarita, nº 695 - Nova Cidade",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/10/30-300x228.png",
    hotsite: "https://livemargarita.hotsite.in/home",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/nova-cidade-premium-2/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "",
  },
  {
    id: "pedro-teixeira-diamante",
    name: "Pedro Teixeira Diamante",
    address: "Av. Pedro Teixeira, 700 - Dom Pedro",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/10/pedro-teixeira-300x228.png",
    hotsite: "https://pedroteixeira.hotsite.in",
    mapLink: "https://maps.app.goo.gl/gdYdzqCxZGafoith7",
    viewLink: "https://www.liveacademia.com.br/unidades/pedro-teixeira-diamante/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/gdYdzqCxZGafoith7",
  },
  {
    id: "planalto-diamante",
    name: "Planalto Diamante",
    address: "Rua Salim Kahane, 3586 - Planalto",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/03/31-300x228.png",
    hotsite: "https://liveplanalto.hotsite.in",
    mapLink: "https://maps.app.goo.gl/xX2g421gBKc8FHDC8",
    viewLink: "https://www.liveacademia.com.br/unidades/planalto-diamante/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/xX2g421gBKc8FHDC8",
  },
  {
    id: "rodrigues-grande-circular",
    name: "Rodrigues Grande Circular Premium",
    address: "Av. Autaz Mirim, 7451 - Tancredo Neves",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/04/21-300x228.png",
    hotsite: "https://liverodrigues.hotsite.in",
    mapLink: "https://maps.app.goo.gl/9Lwpp8SEuwn8Rn1fA",
    viewLink: "https://www.liveacademia.com.br/unidades/rodrigues-grande-circular-premium/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/9Lwpp8SEuwn8Rn1fA",
  },
  {
    id: "torquato-santos-dumont-diamante",
    name: "Torquato Santos Dumont Diamante",
    address: "Av. Torquato Tapajós, 5555, Da Paz",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/33-300x228.png",
    hotsite: "https://livetorquato1.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/qQh4yx98kHz7QQvd9",
    viewLink: "https://www.liveacademia.com.br/unidades/torquato-santos-dumont-diamante/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/qQh4yx98kHz7QQvd9",
  },
  {
    id: "torres-diamante",
    name: "Torres Diamante",
    address: "Rua Mitiko, 397, Parque Dez de Novembro",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/10/34-1-300x228.png",
    hotsite: "https://liveacademiastorres.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/V8a9D7bnWy6WHFgAA",
    viewLink: "https://www.liveacademia.com.br/unidades/torres-premium/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/V8a9D7bnWy6WHFgAA",
  },
  {
    id: "vieiralves-diamante",
    name: "Vieiralves Diamante",
    address: "Av. Djalma Batista, 450 - Nossa Senhora das Graças",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2024/10/35-300x228.png",
    hotsite: "https://liveacademias.hotsite.in/home",
    mapLink: "https://maps.app.goo.gl/V8wACyPE9xaEWMXx9",
    viewLink: "https://www.liveacademia.com.br/unidades/vieiralves-diamante/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/V8wACyPE9xaEWMXx9",
  },
  {
    id: "vitoria-coroado",
    name: "Vitória Coroado Premium",
    address: "Avenida Cosme Ferreira, 1620,  Coroado I - Vitória Supermercados",
    hours: "Seg-Sex: 5h30-22h | Sáb: 7h-15h | Dom: Fechado | Feriado: 7h-12h",
    features: ["Sem fidelidade", "Espaço Relax", "Espaço Yoga", "Studio de Bike", "Aulas coletivas", "Climatização", "App acesso"],
    type: "diamante",
    status: "open",
    logo: "https://www.liveacademia.com.br/wp-content/uploads/2023/12/22-300x228.png",
    hotsite: "https://vitoriacoroado.hotsite.in",
    mapLink: "https://maps.app.goo.gl/ZaaU2WtH7JAQiFxo9",
    viewLink: "https://www.liveacademia.com.br/unidades/vitoria-coroado/",
    planos: [
      { name: "Assinatura Diamante s/ Fidelidade*", price: "199,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" },
      { name: "Assinatura Diamante s/ Fidelidade", price: "179,90" }
    ],
    tourUrl: "https://maps.app.goo.gl/ZaaU2WtH7JAQiFxo9",
  },

  // Unidades em Inauguração
  {
    id: "cachoeirinha-diamante",
    name: "Cachoeirinha Diamante",
    address: "Cachoeirinha - Em breve",
    hours: "Em breve",
    features: [],
    type: "inauguracao",
    status: "coming_soon",
    logo: null,
    hotsite: "https://www.liveacademia.com.br/unidades/cachoeirinha-diamante/",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/cachoeirinha-diamante/",
    planos: [],
    tourUrl: "",
  },
  {
    id: "campos-eliseos-diamante",
    name: "Campos Elíseos Diamante",
    address: "Campos Elíseos - Em breve",
    hours: "Em breve",
    features: [],
    type: "inauguracao", 
    status: "coming_soon",
    logo: null,
    hotsite: "https://www.liveacademia.com.br/unidades/campos-eliseos-diamante/",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/campos-eliseos-diamante/",
    planos: [],
    tourUrl: "",
  },
  {
    id: "morada-sol-diamante",
    name: "Morada do Sol Assinpa Diamante",
    address: "Morada do Sol - Em breve",
    hours: "Em breve",
    features: [],
    type: "inauguracao",
    status: "coming_soon", 
    logo: null,
    hotsite: "https://www.liveacademia.com.br/unidades/morada-do-sol-diamante-2/",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/morada-do-sol-diamante-2/",
    planos: [],
    tourUrl: "",
  },
  {
    id: "veneza-turismo",
    name: "Veneza Turismo",
    address: "Turismo - Em breve",
    hours: "Em breve",
    features: [],
    type: "inauguracao",
    status: "coming_soon",
    logo: null,
    hotsite: "https://www.liveacademia.com.br/unidades/turismo-diamante/",
    mapLink: "",
    viewLink: "https://www.liveacademia.com.br/unidades/turismo-diamante/",
    planos: [],
    tourUrl: "",
  },
]